# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5116

# Company APIS
## POST /api/parkinglots
## GET /api/parkinglots
## GET /api/parkinglots/{parkinglotId}
## PUT /api/parkinglots/{parkinglotId}
## DELETE /api/parkinglots/{parkinglotId}

ParkingLot
{
  "id": "6B29FC40-CA47-1067-B31D-00DD010662DA",
  "name": "AC Parking Structure",
  "capacity": 10,
  "location": "23 W Main St, Los Angeles, CA",
}

CreationParkingLotRequest
{
  "name": "AC Parking Structure",
  "capacity": 10,
  "location": "23 W Main St, Los Angeles, CA",
}

## AC1 Create ParkingLot
POST https://{{hostname}}:{{port}}/api/parkinglots
Content-Type: application/json; charset=utf-8

{
  "name": "AC Parking Structure",
  "capacity": 10,
  "location": "23 W Main St, Los Angeles, CA"
}

## Response:
### Case1:  ParkingLot Created Success, Return ParkingLot created with Status CREATED( 201 )
### Case2:  ParkingLot Name Exsiting, Return 400 BAD REQUEST
### Case3:  ParkingLot capacity less than 10, Return 400 BAD REQUEST
### Case4:  Other Bad Reqeust ( Request Body Not Valid), Return 400 BAD REQUEST

######################################################################################

## AC2 Get All ParkingLots
GET https://{{hostname}}:{{port}}/api/parkinglots

### Response: OK 200 with List of ParkingLots

######################################################################################

## AC3 Get Company By Id
GET https://{{hostname}}:{{port}}/api/parkinglots/{parkinglotId}

### Response: 
### Case1: OK 200 with The ParkingLot Found
### Case2: 404 ParkingLot NOT Found

######################################################################################

## AC4 GET Companies with Paging 
GET https://{{hostname}}:{{port}}/api/companies?pageSize=2&pageIndex=3
### Response: OK 200 with List of Companies

######################################################################################

## AC5 Update Company 
PUT https://{{hostname}}:{{port}}/api/companies/{companyId}
Content-Type: application/json; charset=utf-8

{
  "name": Google
}
### Response: 
### Case1: Sucess, OK 200 NO with updated Company
### Case2: 404 Company NOT Found

######################################################################################

## AC10 Delete Company by ID 
DELETE https://{{hostname}}:{{port}}/api/companies/{companyId}
Content-Type: application/json; charset=utf-8

### Response: 
### Case1:  Company Deleted Success, Return Company with Status NO CONTENT( 204 )
### Case2:  Company Not Found, Return Status NOT FOUND( 404 )

######################################################################################